version: '3.7'
services:
 api:
  build: "./backend"
  networks:
   - "my-network"
  depends_on:
   - "db"

 db:
  build: "./PG"
  networks:
   - "my-network"

 web:
  build: "./web"
  networks:
   - "my-network"

 httpd:
  build: "./reverseProxy"
  ports:
   - "80:80"
   - "8080:8080"
  networks:
   - "my-network"
  depends_on:
   - "api"
   - "web"
   - "front"
   
 front:
  build: "./devops-front"
  networks:
   - "my-network"
  depends_on:
   - "api"
networks:
 my-network:
  name: network01