name: CI DevOps 2022 CPE 
on:
  push:
    branches: 
      - main
  pull_request:
jobs:
  test-backend:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build and test with Maven
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=DEVOPS2022 -Dsonar.organization=tomecher -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{secrets.SONAR_TOKEN }} --file TP01/backend/simple-api/pom.xml
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_PASSWORD }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build image and push backend
      uses: docker/build-push-action@v2
      with:
        push: ${{ github.ref == 'refs/heads/main' }}
        context: ./TP01/backend
        tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-cpe:backend
    - name: Build image and push db
      uses: docker/build-push-action@v2
      with:
        push: ${{ github.ref == 'refs/heads/main' }}
        context: ./TP01/PG
        tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-cpe:database
    - name: Build image and push reverse proxy
      uses: docker/build-push-action@v2
      with:
        push: ${{ github.ref == 'refs/heads/main' }}
        context: ./TP01/reverseProxy
        tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-cpe:rproxy
    - name: Build image and push apache
      uses: docker/build-push-action@v2
      with:
        push: ${{ github.ref == 'refs/heads/main' }}
        context: ./TP01/web
        tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-cpe:web
  